# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build -c $(buildconfiguration)
- script: dotnet test --no-build --no-restore -c $(buildconfiguration) --logger trx
- script: dotnet publish **/Web.csproj -c $(buildconfiguration) -o $(build.artifactstagingdirectory)/www
- script: dotnet publish **/CLI.csproj --runtime win10-x64 -c $(buildconfiguration) -o $(build.artifactstagingdirectory)/win 
- script: dotnet publish **/CLI.csproj --runtime osx-x64 -c $(buildconfiguration) -o $(build.artifactstagingdirectory)/osx

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/*.trx'
    mergeTestResults: true
    failTaskOnFailedTests: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/www'
    ArtifactName: 'www'
    publishLocation: 'Container'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/win'
    ArtifactName: 'win'
    publishLocation: 'Container'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/osx'
    ArtifactName: 'osx'
    publishLocation: 'Container'