trigger:
- master

parameters:
  - name: buildConfiguration
    type: string 
    default: Release

pool:
  vmImage: 'ubuntu-latest'

steps:

# BUILD
- task: UseDotNet@2 
  displayName: "install .NET Core 3.1.x"
  inputs:
    version: '3.1.x'
    packageType: sdk

# TEST   
- script: dotnet test -c ${{parameters.buildconfiguration}} --logger trx
  displayName: test
- task: PublishTestResults@2
  displayName: upload test results
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/*.trx'
    mergeTestResults: true
    failTaskOnFailedTests: true

# PUBLISH WINDOWS APP
- script: dotnet publish **/CLI.csproj -c ${{parameters.buildconfiguration}} -o $(build.artifactstagingdirectory)/win /p:PublishSingleFile=true -r win10-x64
  displayName: publish windows CLI
- publish: $(build.artifactstagingdirectory)/win
  artifact: win

# PUBLISH MACOS APP
- script: dotnet publish **/CLI.csproj -c ${{parameters.buildconfiguration}} -o $(build.artifactstagingdirectory)/osx /p:PublishSingleFile=true -r osx-x64
  displayName: publish macOS CLI
- publish: $(build.artifactstagingdirectory)/osx
  artifact: osx