trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
#
# build
- script: dotnet build -c $(buildconfiguration)
- script: dotnet test --no-build --no-restore -c $(buildconfiguration) --logger trx
- script: dotnet publish **/Web.csproj -c $(buildconfiguration) -o $(build.artifactstagingdirectory)/www
- script: dotnet publish **/CLI.csproj --runtime win10-x64 -c $(buildconfiguration) -o $(build.artifactstagingdirectory)/win 
- script: dotnet publish **/CLI.csproj --runtime osx-x64 -c $(buildconfiguration) -o $(build.artifactstagingdirectory)/osx

#
# publish
- publish: $(build.artifactstagingdirectory)/www
  artifact: www
- publish: $(build.artifactstagingdirectory)/win
  artifact: win
- publish: $(build.artifactstagingdirectory)/osx
  artifact: osx

#
# test results
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/*.trx'
    mergeTestResults: true
    failTaskOnFailedTests: true