# pr pipeline
trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
- name: buildConfiguration
  type: string 
  default: Release

steps:
- task: UseDotNet@2 
  displayName: "install .NET Core 3.1.x"
  inputs:
    version: '3.1.x'
    packageType: sdk
    
- script: dotnet test Tests -c $(buildconfiguration) --logger trx
  displayName: test

- task: PublishTestResults@2
  displayName: upload test results
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/*.trx'
    mergeTestResults: true
    failTaskOnFailedTests: true