# deployment
#
# kubecutl
# $ kubectl create secret docker-registry pullsecret --docker-server=https://ghcr.io/ --docker-username=notneeded --docker-password=$GHCR_PAT
# $ kubectl apply -f k8_deployment.yaml
# $ kubectl get service
# 

#
# describe app deployment
#
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: portfolio-deployment
  labels:
    app: portfolio

spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio

  template:
    metadata:
      labels:
        app: portfolio

    spec:
      # imagePullSecrets:
      #   - name: pullsecret
      containers:
        - name: portfolio
          image: ghcr.io/zachariahcox/portfolio
          ports:
          - containerPort: 80
          