name: ci

on:
  push:
    branches: [ master ]

env:
  image_name: ghcr.io/zachariahcox/portfolio
  version: ${{github.run_id}}

jobs:
  do_everything:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    # `$ echo $GHCR_PAT | docker login ghcr.io -u $GHCR_USER --password-stdin`
    - uses: Azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_PAT }}
    
    # there should probably be a task for this too?
    - run: |
        docker build . -t ${{env.image_name}}:${{env.version}}
        docker push ${{env.image_name}}:${{env.version}}
      
    # connect kubectl to our aks sub. 
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{secrets.AZURE_CREDENTIALS}}'
        resource-group: portfoliopicker
        cluster-name: kluster
    
    # moral equivalent of `$ kubectl create secret docker-registry portfolio-pull-secret --docker-server=https://ghcr.io/ --docker-username=notneeded --docker-password=$GHCR_PAT`
    - uses: Azure/k8s-create-secret@v1
      with:
        container-registry-url: https://ghcr.io/
        container-registry-username: notneeded
        container-registry-password: ${{secrets.GHCR_PAT}}
        secret-name: portfolio-pull-secret

    # `$ kubectl apply -f k8_deployment.yml`
    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          ${{env.image_name}}:${{env.version}}
        imagepullsecrets: |
          portfolio-pull-secret
